name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm install
      - run: npm run build
      - run: npm run deploy
#      - name: Deploy
#        uses: nguyenhuuluan94/oivan@0.0.0
#        with:
#          target_branch: gh-pages
#          build_dir: build
#        env:
#          GITHUB_TOKEN: ${{ secrets.OIVAN_REPO_TOKEN }}
